name: Static Analysis

on:
  push:

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: init_src_pillar
        run: |
          TAG=$(cat .terraform-version)
          cd src/pillar
          sed -i -e 's/  backend "azurerm" {}//g' 99_main.tf # use local backend
          docker run -v $(pwd):/tmp -w /tmp hashicorp/terraform:$TAG init

      - name: init_src_core
        run: |
          TAG=$(cat .terraform-version)
          cd src/core
          sed -i -e 's/  backend "azurerm" {}//g' 99_main.tf # use local backend
          docker run -v $(pwd):/tmp -w /tmp hashicorp/terraform:$TAG init

      - name: init_src_k8s
        run: |
          TAG=$(cat .terraform-version)
          cd src/k8s
          sed -i -e 's/  backend "azurerm" {}//g' 99_main.tf # use local backend
          docker run -v $(pwd):/tmp -w /tmp hashicorp/terraform:$TAG init

      - name: run_test
        run: |
          TAG=nightly
          docker run -v $(pwd):/lint -w /lint ghcr.io/antonbabenko/pre-commit-terraform:$TAG run -a
